import {
  LucideArrowDown as ArrowDown,
  LucideArrowUp as ArrowUp,
  LucideBell as Bell,
  LucideChartBar as ChartBar,
  LucideChevronLeft as ChevronLeft,
  LucideChevronRight as ChevronRight,
  LucideCircleUser as CircleUser,
  LucideX as X,
  LucideCirclePause as CirclePause,
  LucideClipboardList as ClipboardList,
  LucideDownload as Download,
  LucideExternalLink as ExternalLink,
  LucideEye as Eye,
  LucideFilePenLine as FilePenLine,
  LucideLayoutGrid as LayoutGrid,
  LucideLayoutDashboard as LayoutDashboard,
  LucideMegaphone as Megaphone,
  LucideMoon as Moon,
  LucideMenu as Menu,
  LucidePlus as Plus,
  LucideRoute as Route,
  LucideSearch as Search,
  LucideSettings as Settings,
  LucideSun as Sun,
  LucideUserCheck as UserCheck,
} from '@lucide/angular';

export const LUCIDE_ICONS = {
  ArrowDown,
  ArrowUp,
  Bell,
  ChartBar,
  ChevronLeft,
  ChevronRight,
  CircleUser,
  X,
  CirclePause,
  ClipboardList,
  Download,
  ExternalLink,
  Eye,
  FilePenLine,
  LayoutGrid,
  LayoutDashboard,
  Megaphone,
  Moon,
  Menu,
  Plus,
  Route,
  Search,
  Settings,
  Sun,
  UserCheck,
} as const;
